# Generated by Django 5.2.15 on 2026-06-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroClasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(choices=[('Reciclable', 'Reciclable'), ('No Reciclable', 'No Reciclable'), ('Aprovechable', 'Aprovechable'), ('Infeccioso', 'Infeccioso')], max_length=50)),
                ('tipo', models.CharField(max_length=100)),
                ('utilidad', models.FloatField(default=0)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('peso_unitario_kg', models.DecimalField(decimal_places=3, default=0, max_digits=8)),
                ('ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egreso', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='usuarios.perfil')),
            ],
        ),
    ]
