# Generated by Django 6.0.6 on 2026-06-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClasificacionResiduos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroclasificacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
