# Generated by Django 5.2.15 on 2026-06-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClasificacionResiduos', '0002_alter_registroclasificacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroclasificacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
