# Generated by Django 5.2.15 on 2026-06-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_residuos', models.PositiveIntegerField(default=0)),
                ('reciclables', models.PositiveIntegerField(default=0)),
                ('no_reciclables', models.PositiveIntegerField(default=0)),
                ('aprovechables', models.PositiveIntegerField(default=0)),
                ('infecciosos', models.PositiveIntegerField(default=0)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egreso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadistica_residuos', to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_residuos', models.PositiveIntegerField(default=0)),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egreso_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to='usuarios.perfil')),
            ],
        ),
    ]
